In [2]:
import pandas as pd
import geopandas as gpd

pd.set_option('display.max_columns', None)

In [3]:
denue = gpd.read_file('../datos/01_procesos/unidades_economicas_2025.gpkg')
denue.head(1)

,id,clee,nom_estab,raz_social,codigo_act,nombre_act,per_ocu,tipo_vial,nom_vial,tipo_v_e_1,nom_v_e_1,tipo_v_e_2,nom_v_e_2,tipo_v_e_3,nom_v_e_3,numero_ext,letra_ext,edificio,edificio_e,numero_int,letra_int,tipo_asent,nomb_asent,tipoCenCom,nom_CenCom,num_local,cod_postal,cve_ent,entidad,cve_mun,municipio,cve_loc,localidad,ageb,manzana,telefono,correoelec,www,tipoUniEco,latitud,longitud,fecha_alta,layer,path,cod_sector,sector,cod_subsector,subsector,cod_rama,rama,cod_subrama,subrama,clase,geometry
0,7400578,09002722517001121000000000U0,PIZZAS VENECIA,None,722517,Restaurantes con servicio de preparaci�n de pi...,0 a 5 personas,CALLE,CAMPO CANTEMOC,CALLE,EUFEMIO ZAPATA,CALLE,GENOVEVO DE LA O.,CALLE,SEGUNDA CERRADA DEMOCRACIAS,143,A,143A,PLANTA BAJA,0,143A,COLONIA,SAN MIGUEL AMANTLA,None,None,None,02700,09,Ciudad de M�xico,002,Azcapotzalco,0001,Azcapotzalco,0631,048,5553527613,None,None,Fijo,19.478754,-99.203788,2019-11,denue_09_shp — conjunto_de_datos/denue_inegi_0...,/vsizip/C:\Users\COMIMSA\Downloads\denue_09_sh...,72,Servicios de alojamiento temporal y de prepara...,722,Servicios de preparación de alimentos y bebidas,7225,Servicios de preparación de alimentos y bebida...,72251,Servicios de preparación de alimentos y bebida...,Restaurantes con servicio de preparación de pi...,POINT (478613.424 2153814.635)

In [4]:
denue['rama'].unique()

array(['Servicios de preparación de alimentos y bebidas alcohólicas y no alcohólicas',
       'Comercio al por menor de mobiliario, equipo y accesorios de cómputo, teléfonos y otros aparatos de comunicación',
       'Comercio al por menor en tiendas de autoservicio',
       'Reparación y mantenimiento de automóviles y camiones',
       'Comercio al por menor de artículos de ferretería, tlapalería y vidrios',
       'Salones y clínicas de belleza, baños públicos y bolerías ',
       'Comercio al por menor de ropa, bisutería y accesorios de vestir',
       'Comercio al por menor de abarrotes y alimentos',
       'Comercio al por menor de artículos para el cuidado de la salud',
       'Reparación y mantenimiento de artículos para el hogar y personales',
       'Asociaciones y organizaciones religiosas, políticas y civiles ',
       'Comercio al por menor de muebles para el hogar y otros enseres domésticos',
       'Centros nocturnos, bares, cantinas y similares',
       'Consultorios dentales',
       'Comercio al por menor de mascotas y sus accesorios, regalos, artículos religiosos, desechables, artesanías y otros artículos de uso personal',
       'Comercio al por menor de artículos de perfumería y joyería',
       'Comercio al por menor de artículos usados',
       'Comercio al por menor de artículos para la decoración de interiores',
       'Comercio al por menor de artículos para el esparcimiento',
       'Otros servicios educativos', 'Servicios de empleo',
       'Servicios de limpiezaT ',
       'Escuelas de educación básica, media y para necesidades especiales',
       'Comercio al por menor de bebidas, hielo y tabaco',
       'Comercio al por menor de automóviles y camionetas',
       'Comercio al por menor de artículos de papelería, libros, revistas y periódicos',
       'Comercio al por menor de productos textiles, excepto ropa',
       'Comercio al por menor de partes y refacciones para automóviles, camionetas y camiones',
       'Servicios de preparación de alimentos por encargo',
       'Hoteles, moteles y similares',
       'Servicios de apoyo secretarial, fotocopiado, cobranza, investigación crediticia y similares',
       'Recolección de residuos',
       'Reparación y mantenimiento de maquinaria y equipo agropecuario, industrial, comercial y de servicios',
       'Comercio al por menor de motocicletas y otros vehículos de motor',
       'Comercio al por menor de calzado',
       'Servicios de investigación, protección y seguridad',
       'Servicios integrales de apoyo a los negocios en instalaciones',
       'Intermediación de comercio al por menor, y comercio al por menor a través de catálogos impresos, televisión y similares',
       'Servicios de administración de negocios',
       'Escuelas de educación superior',
       'Comercio al por menor en tiendas departamentales',
       'Parques con instalaciones recreativas y casas de juegos electrónicos',
       'Servicios de arquitectura, ingeniería y actividades relacionadas',
       'Otros servicios profesionales, científicos y técnicos',
       'Comercio al por menor de combustibles, aceites y grasas lubricantes',
       'Servicios de consultoría administrativa, científica y técnica',
       'Otros servicios recreativos', 'Diseño especializado',
       'Servicios de publicidad y actividades relacionadas',
       'Dirección y administración de grupos empresariales o corporativos',
       'Servicios de diseño de sistemas de cómputo y servicios relacionadosT ',
       'Servicios de contabilidad, auditoría y servicios relacionados',
       'Asociaciones y organizaciones comerciales, laborales, profesionales y recreativas',
       'Reparación y mantenimiento de equipo electrónico y de equipo de precisión',
       'Promotores de espectáculos artísticos, culturales, deportivos y similares',
       'Artistas, escritores y técnicos independientes',
       'Casinos, loterías y otros juegos de azar', 'Servicios legales',
       'Museos, sitios históricos, zoológicos y similares',
       'Estacionamientos y pensiones para vehículos automotores',
       'Agencias de viajes y servicios de reservaciones',
       'Compañías y grupos de espectáculos artísticos y culturales',
       'Servicios de orientación y trabajo social', 'Guarderías',
       'Actividades administrativas de instituciones de bienestar social ',
       'Administración pública en general ',
       'Residencias para el cuidado de personas con problemas de retardo mental, trastorno mental y adicciones',
       'Hospitales generales',
       'Otros consultorios para el cuidado de la salud',
       'Consultorios médicos',
       'Impartición de justicia y mantenimiento de la seguridad y el orden público ',
       'Regulación y fomento de actividades para mejorar y preservar el medio ambiente ',
       'Laboratorios médicos y de diagnóstico',
       'Regulación y fomento del desarrollo económico ',
       'Actividades de seguridad nacional ',
       'Servicios de capacitación para el trabajo para personas desempleadas, subempleadas o con discapacidad',
       'Lavanderías y tintorerías',
       'Servicios de remediación, recuperación, y otros servicios de manejo de residuos',
       'Escuelas comerciales, de computación y de capacitación para ejecutivos',
       'Pensiones y casas de huéspedes, y departamentos y casas amueblados con servicios de hotelería',
       'Escuelas de oficios',
       'Servicios funerarios y administración de cementerios',
       'Otros servicios de apoyo a los negocios',
       'Comercio al por mayor de mobiliario y equipo de cómputo y de oficina, y de otra maquinaria y equipo de uso general',
       'Comercio al por mayor de maquinaria y equipo para la industria',
       'Comercio al por mayor de materias primas para la industria',
       'Comercio al por mayor de productos textiles y calzado',
       'Comercio al por mayor de maquinaria y equipo para los servicios y para actividades comerciales',
       'Comercio al por mayor de abarrotes y alimentos',
       'Comercio al por mayor de electrodomésticos menores y aparatos de línea blanca',
       'Comercio al por mayor de camiones y de partes y refacciones nuevas para automóviles, camionetas y camiones',
       'Comercio al por mayor de productos farmacéuticos',
       'Orfanatos y otras residencias de asistencia social',
       'Comercio al por mayor de materiales de desecho',
       'Comercio al por mayor de artículos de papelería, libros, revistas y periódicos',
       'Intermediación de comercio al por mayor',
       'Comercio al por mayor de maquinaria y equipo agropecuario, forestal y para la pesca',
       'Comercio al por mayor de grabaciones de audio y video en medios físicos, juguetes y artículos deportivos',
       'Comercio al por mayor de materias primas agropecuarias y forestales',
       'Comercio al por mayor de bebidas, hielo y tabaco',
       'Escuelas de educación técnica superior',
       'Servicios de revelado e impresión de fotografías y otros servicios personales',
       'Asilos y otras residencias para el cuidado de ancianos',
       'Servicios comunitarios de alimentación, refugio y emergencia',
       'Comercio al por mayor de artículos de perfumería, cosméticos y joyería',
       'Hospitales de otras especialidades médicasT ',
       'Servicios de ambulancias, de bancos de órganos y otros servicios auxiliares al tratamiento médico',
       'Centros para la atención de pacientes que no requieren hospitalización',
       'Fabricación de muebles, excepto de oficina y estantería',
       'Fabricación de estructuras metálicas y productos de herrería',
       'Fabricación de otros productos metálicos',
       'Fabricación de colchones, persianas y cortineros',
       'Fabricación de maquinaria y equipo para el comercio y los servicios',
       'Fabricación de productos de hierro y acero',
       'Otras industrias manufactureras',
       'Fabricación de partes para vehículos automotores',
       'Fabricación de productos metálicos forjados y troquelados',
       'Maquinado de piezas y fabricación de tornillos',
       'Fabricación de muebles de oficina y estantería',
       'Recubrimientos y terminados metálicos',
       'Fabricación de equipo de generación y distribución de energía eléctrica',
       'Fabricación de equipo de aire acondicionado, calefacción, y de refrigeración industrial y comercial',
       'Fabricación de aparatos eléctricos de uso doméstico',
       'Fabricación de componentes electrónicos',
       'Fabricación de equipo no electrónico y material desechable de uso médico, dental y para laboratorio, y artículos oftálmicos',
       'Fabricación de maquinaria y equipo para las industrias manufactureras, excepto la metalmecánica',
       'Fabricación de herramientas de mano sin motor y utensilios de cocina metálicos',
       'Fabricación de alambre, productos de alambre y resortes',
       'Fabricación de calderas, tanques y envases metálicos',
       'Fabricación de accesorios de iluminación',
       'Fabricación y reproducción de medios magnéticos y ópticos',
       'Fabricación de otra maquinaria y equipo para la industria en general',
       'Fabricación de otros equipos y accesorios eléctricos',
       'Moldeo por fundición de piezas metálicas',
       'Tratamiento y disposición final de residuos',
       'Fabricación de instrumentos de medición, control, navegación, y equipo médico electrónico',
       'Fabricación de maquinaria y equipo para la industria metalmecánica',
       'Fabricación de motores de combustión interna, turbinas y transmisiones',
       'Industrias de metales no ferrosos, excepto aluminio',
       'Industria básica del aluminio',
       'Hospitales psiquiátricos y para el tratamiento por adicción',
       'Residencias con cuidados de enfermeras para enfermos convalecientes, en rehabilitación, incurables y terminales',
       'Banca múltiple', 'Elaboración de productos lácteos',
       'Elaboración de productos de panadería y tortillas',
       'Alquiler de maquinaria y equipo agropecuario, pesquero, industrial, comercial y de servicios',
       'Acabado de productos textiles y fabricación de telas recubiertas',
       'Industria de las bebidas',
       'Fabricación de otros productos textiles, excepto prendas de vestirT ',
       'Alquiler sin intermediación de bienes raíces',
       'Inmobiliarias y corredores de bienes raíces',
       'Alquiler de artículos para el hogar y personales',
       'Alquiler de automóviles, camiones y otros transportes terrestres',
       'Servicios relacionados con los servicios inmobiliarios',
       'Fabricación de calzado', 'Fabricación de telas',
       'Matanza, empacado y procesamiento de carne de ganado, aves y otros animales comestibles',
       'Confección de prendas de vestirT ',
       'Otras industrias alimentarias', 'Compañías de seguros y fianzas',
       'Otras instituciones de intermediación crediticia y financiera no bursátil',
       'Fabricación de productos de plástico',
       'Impresión e industrias conexas',
       'Servicios relacionados con los seguros y las fianzas, y administración de fondos para el retiro',
       'Centros generales de alquiler',
       'Confección de alfombras, blancos y similares',
       'Instalaciones y equipamiento en construcciones',
       'Captación, tratamiento y suministro de agua',
       'Molienda de granos y de semillas y obtención de aceites y grasas',
       'Fabricación de otros productos de cuero, piel y materiales sucedáneos',
       'Suministro de gas natural por ductos al consumidor final',
       'Edificación no residencial',
       'Generación, transmisión, distribución y comercialización de energía eléctrica',
       'Confección de accesorios de vestir y otras prendas de vestir no clasificados en otra parte',
       'Fabricación de prendas de vestir de tejido de punto',
       'Preparación e hilado de fibras textiles, y fabricación de hilos',
       'Casas de bolsa, casas de cambio y centros cambiarios',
       'Servicios de alquiler de marcas registradas, patentes y franquicias',
       'Instituciones financieras de fomento económico',
       'Otros trabajos especializados para la construcción',
       'Operadores de servicios de telecomunicaciones alámbricas e inalámbricas',
       'Otros servicios de telecomunicaciones',
       'Uniones de crédito e instituciones de ahorro',
       'Cimentaciones, montaje de estructuras prefabricadas y trabajos en exteriores',
       'Edificación residencial', 'Trabajos de acabados en edificaciones',
       'Conservación de frutas, verduras, guisos y otros alimentos preparados',
       'Servicios de mensajería y paquetería foránea',
       'Industria fílmica y del videoT ', 'Servicios de almacenamiento',
       'Servicios postales', 'Servicios de mensajería y paquetería local',
       'Acuicultura',
       'Elaboración de azúcares, chocolates, dulces y similares',
       'Servicios de investigación científica y desarrollo',
       'Construcción de vías de comunicación',
       'Provisión de infraestructura de servicios de cómputo, procesamiento de datos, hospedaje de páginas de internet y otros servicios relacionados',
       'Bibliotecas, archivos, portales de búsqueda en la red y otros servicios de suministro de información',
       'Construcción de obras para el suministro de agua, petróleo, gas, energía eléctrica y telecomunicaciones',
       'Edición de periódicos, revistas, libros, directorios y otros materiales',
       'Industria del sonido',
       'Operadores de servicios de telecomunicaciones vía satéliteT ',
       'Otras construcciones de ingeniería civil',
       'Elaboración de alimentos balanceados para animales',
       'Curtido y acabado de cuero y piel', 'Edición de software',
       'Fabricación de productos a base de arcillas y minerales refractarios',
       'Fabricación de otros productos químicos',
       'Fabricación de productos de cartón y papel',
       'Fabricación de laminados y aglutinados de madera',
       'Fabricación de cemento, concreto y sus productos',
       'Fabricación de vidrio y productos de vidrio',
       'Fabricación de otros productos de madera',
       'Fabricación de pulpa, papel y cartón',
       'Fabricación de productos de hule',
       'Fabricación de jabones, limpiadores y preparaciones de tocador',
       'Fabricación de otros productos a base de minerales no metálicos',
       'Fabricación de equipo de comunicación',
       'Fabricación de carrocerías y remolques',
       'Fabricación de productos farmacéuticos',
       'Fabricación de fertilizantes, plaguicidas y otros agroquímicos',
       'Fabricación de equipo de audio y de video',
       'Fabricación de herrajes y cerraduras',
       'Fabricación de computadoras y equipo periférico',
       'Fabricación de otro equipo de transporte',
       'Fabricación de productos derivados del petróleo y del carbón',
       'Fabricación de resinas y hules sintéticos, y fibras químicas',
       'Aserrado y conservación de la madera',
       'Fabricación de productos químicos básicos',
       'Fabricación de pinturas, recubrimientos y adhesivos',
       'Servicios relacionados con la intermediación crediticia no bursátil',
       'Servicios de intermediación para el transporte de carga',
       'Autotransporte de carga general',
       'Transporte colectivo foráneo de pasajeros de ruta fija',
       'Autotransporte de carga especializado',
       'Transporte escolar y de personal',
       'Servicios relacionados con el transporte por carreteraT ',
       'Servicios relacionados con el transporte por agua',
       'Transporte turístico por tierraT ',
       'Transporte colectivo urbano y suburbano de pasajeros de ruta fija',
       'Otros servicios relacionados con el transporte',
       'Servicios relacionados con el transporte por ferrocarril',
       'Servicio de taxis y limusinas', 'Transporte aéreo regular',
       'Alquiler de autobuses con chofer', 'Transporte por ferrocarril'],
      dtype=object)

In [5]:
# Clasificación de ramas económicas relacionadas con el CDIT Vallejo-i
# Agrupadas en 6 categorías temáticas

ramas_cdit = {
    'Tecnología, informática y telecomunicaciones': [
        'Servicios de diseño de sistemas de cómputo y servicios relacionadosT ',
        'Servicios de investigación científica y desarrollo',
        'Edición de software',
        'Provisión de infraestructura de servicios de cómputo, procesamiento de datos, hospedaje de páginas de internet y otros servicios relacionados',
        'Operadores de servicios de telecomunicaciones alámbricas e inalámbricas',
        'Otros servicios de telecomunicaciones',
        'Operadores de servicios de telecomunicaciones vía satéliteT ',
        'Bibliotecas, archivos, portales de búsqueda en la red y otros servicios de suministro de información',
        'Comercio al por menor de mobiliario, equipo y accesorios de cómputo, teléfonos y otros aparatos de comunicación',
        'Comercio al por mayor de mobiliario y equipo de cómputo y de oficina, y de otra maquinaria y equipo de uso general',
    ],
    'Diseño y economía creativa': [
        'Diseño especializado',
        'Servicios de publicidad y actividades relacionadas',
        'Artistas, escritores y técnicos independientes',
        'Compañías y grupos de espectáculos artísticos y culturales',
        'Promotores de espectáculos artísticos, culturales, deportivos y similares',
        'Industria fílmica y del videoT ',
        'Industria del sonido',
        'Edición de periódicos, revistas, libros, directorios y otros materiales',
        'Museos, sitios históricos, zoológicos y similares',
    ],
    'Manufactura tecnológica e industria avanzada': [
        'Fabricación de computadoras y equipo periférico',
        'Fabricación de componentes electrónicos',
        'Fabricación de equipo de comunicación',
        'Fabricación de equipo de audio y de video',
        'Fabricación de instrumentos de medición, control, navegación, y equipo médico electrónico',
        'Fabricación de maquinaria y equipo para el comercio y los servicios',
        'Fabricación de equipo de generación y distribución de energía eléctrica',
        'Fabricación de aparatos eléctricos de uso doméstico',
        'Fabricación y reproducción de medios magnéticos y ópticos',
        'Fabricación de maquinaria y equipo para la industria metalmecánica',
        'Impresión e industrias conexas',
    ],
    'Servicios profesionales, científicos y técnicos': [
        'Servicios de arquitectura, ingeniería y actividades relacionadas',
        'Otros servicios profesionales, científicos y técnicos',
        'Servicios de consultoría administrativa, científica y técnica',
        'Servicios de administración de negocios',
        'Dirección y administración de grupos empresariales o corporativos',
        'Servicios de contabilidad, auditoría y servicios relacionados',
        'Servicios legales',
    ],
    'Educación y capacitación': [
        'Escuelas de educación superior',
        'Escuelas de educación técnica superior',
        'Escuelas comerciales, de computación y de capacitación para ejecutivos',
        'Escuelas de oficios',
        'Otros servicios educativos',
        'Servicios de capacitación para el trabajo para personas desempleadas, subempleadas o con discapacidad',
    ],
    'Apoyo a negocios y emprendimiento': [
        'Servicios integrales de apoyo a los negocios en instalaciones',
        'Otros servicios de apoyo a los negocios',
        'Servicios de empleo',
        'Servicios de apoyo secretarial, fotocopiado, cobranza, investigación crediticia y similares',
    ],
}

# Mapeo inverso: rama -> categoría
rama_a_categoria = {
    rama: categoria
    for categoria, ramas in ramas_cdit.items()
    for rama in ramas
}

print(f"Total de categorías: {len(ramas_cdit)}")
print(f"Total de ramas clasificadas: {len(rama_a_categoria)}")

Total de categorías: 6
Total de ramas clasificadas: 47

In [6]:
# Agregar columna de categoría CDIT y filtrar unidades relacionadas
denue['categoria_cdit'] = denue['rama'].map(rama_a_categoria)

denue_cdit = denue[denue['categoria_cdit'].notna()].copy()

print(f"Total unidades económicas en la zona: {len(denue):,}")
print(f"Unidades relacionadas con el CDIT:    {len(denue_cdit):,}")
print(f"Proporción: {len(denue_cdit)/len(denue)*100:.1f}%")
print()
print("Distribución por categoría:")
conteo = denue_cdit.groupby('categoria_cdit').size().sort_values(ascending=False).rename('unidades')
print(conteo.to_string())

Total unidades económicas en la zona: 37,459
Unidades relacionadas con el CDIT:    2,200
Proporción: 5.9%

Distribución por categoría:
categoria_cdit
Servicios profesionales, científicos y técnicos    569
Tecnología, informática y telecomunicaciones       481
Apoyo a negocios y emprendimiento                  362
Educación y capacitación                           306
Manufactura tecnológica e industria avanzada       262
Diseño y economía creativa                         220

In [7]:
# Detalle por rama dentro de cada categoría
detalle = (
    denue_cdit
    .groupby(['categoria_cdit', 'rama'])
    .size()
    .reset_index(name='unidades')
    .sort_values(['categoria_cdit', 'unidades'], ascending=[True, False])
)
detalle

,categoria_cdit,rama,unidades
1,Apoyo a negocios y emprendimiento,"Servicios de apoyo secretarial, fotocopiado, c...",310
2,Apoyo a negocios y emprendimiento,Servicios de empleo,30
0,Apoyo a negocios y emprendimiento,Otros servicios de apoyo a los negocios,15
3,Apoyo a negocios y emprendimiento,Servicios integrales de apoyo a los negocios e...,7
12,Diseño y economía creativa,Servicios de publicidad y actividades relacion...,69
6,Diseño y economía creativa,Diseño especializado,56
11,Diseño y economía creativa,"Promotores de espectáculos artísticos, cultura...",32
9,Diseño y economía creativa,Industria fílmica y del videoT,16
7,Diseño y economía creativa,"Edición de periódicos, revistas, libros, direc...",15
4,Diseño y economía creativa,"Artistas, escritores y técnicos independientes",12
10,Diseño y economía creativa,"Museos, sitios históricos, zoológicos y similares",9
8,Diseño y economía creativa,Industria del sonido,6
5,Diseño y economía creativa,Compañías y grupos de espectáculos artísticos ...,5
17,Educación y capacitación,Otros servicios educativos,176
14,Educación y capacitación,Escuelas de educación superior,92
16,Educación y capacitación,Escuelas de oficios,24
13,Educación y capacitación,"Escuelas comerciales, de computación y de capa...",7
15,Educación y capacitación,Escuelas de educación técnica superior,5
18,Educación y capacitación,Servicios de capacitación para el trabajo para...,2
29,Manufactura tecnológica e industria avanzada,Impresión e industrias conexas,224
24,Manufactura tecnológica e industria avanzada,Fabricación de equipo de generación y distribu...,10
19,Manufactura tecnológica e industria avanzada,Fabricación de aparatos eléctricos de uso domé...,6
20,Manufactura tecnológica e industria avanzada,Fabricación de componentes electrónicos,6
25,Manufactura tecnológica e industria avanzada,"Fabricación de instrumentos de medición, contr...",5
27,Manufactura tecnológica e industria avanzada,Fabricación de maquinaria y equipo para la ind...,3
21,Manufactura tecnológica e industria avanzada,Fabricación de computadoras y equipo periférico,2
22,Manufactura tecnológica e industria avanzada,Fabricación de equipo de audio y de video,2
26,Manufactura tecnológica e industria avanzada,Fabricación de maquinaria y equipo para el com...,2
23,Manufactura tecnológica e industria avanzada,Fabricación de equipo de comunicación,1
28,Manufactura tecnológica e industria avanzada,Fabricación y reproducción de medios magnético...,1
31,"Servicios profesionales, científicos y técnicos","Otros servicios profesionales, científicos y t...",293
36,"Servicios profesionales, científicos y técnicos",Servicios legales,72
35,"Servicios profesionales, científicos y técnicos","Servicios de contabilidad, auditoría y servici...",69
33,"Servicios profesionales, científicos y técnicos","Servicios de arquitectura, ingeniería y activi...",65
34,"Servicios profesionales, científicos y técnicos","Servicios de consultoría administrativa, cient...",50
32,"Servicios profesionales, científicos y técnicos",Servicios de administración de negocios,11
30,"Servicios profesionales, científicos y técnicos",Dirección y administración de grupos empresari...,9
39,"Tecnología, informática y telecomunicaciones","Comercio al por menor de mobiliario, equipo y ...",238
38,"Tecnología, informática y telecomunicaciones",Comercio al por mayor de mobiliario y equipo d...,144
37,"Tecnología, informática y telecomunicaciones","Bibliotecas, archivos, portales de búsqueda en...",29
41,"Tecnología, informática y telecomunicaciones",Operadores de servicios de telecomunicaciones ...,27
45,"Tecnología, informática y telecomunicaciones",Servicios de diseño de sistemas de cómputo y s...,21
43,"Tecnología, informática y telecomunicaciones",Otros servicios de telecomunicaciones,12
46,"Tecnología, informática y telecomunicaciones",Servicios de investigación científica y desarr...,5
42,"Tecnología, informática y telecomunicaciones",Operadores de servicios de telecomunicaciones ...,2
44,"Tecnología, informática y telecomunicaciones",Provisión de infraestructura de servicios de c...,2
40,"Tecnología, informática y telecomunicaciones",Edición de software,1

In [8]:
denue.head()

,id,clee,nom_estab,raz_social,codigo_act,nombre_act,per_ocu,tipo_vial,nom_vial,tipo_v_e_1,nom_v_e_1,tipo_v_e_2,nom_v_e_2,tipo_v_e_3,nom_v_e_3,numero_ext,letra_ext,edificio,edificio_e,numero_int,letra_int,tipo_asent,nomb_asent,tipoCenCom,nom_CenCom,num_local,cod_postal,cve_ent,entidad,cve_mun,municipio,cve_loc,localidad,ageb,manzana,telefono,correoelec,www,tipoUniEco,latitud,longitud,fecha_alta,layer,path,cod_sector,sector,cod_subsector,subsector,cod_rama,rama,cod_subrama,subrama,clase,geometry,categoria_cdit
0,7400578,09002722517001121000000000U0,PIZZAS VENECIA,None,722517,Restaurantes con servicio de preparaci�n de pi...,0 a 5 personas,CALLE,CAMPO CANTEMOC,CALLE,EUFEMIO ZAPATA,CALLE,GENOVEVO DE LA O.,CALLE,SEGUNDA CERRADA DEMOCRACIAS,143,A,143A,PLANTA BAJA,0,143A,COLONIA,SAN MIGUEL AMANTLA,None,None,None,02700,09,Ciudad de M�xico,002,Azcapotzalco,0001,Azcapotzalco,0631,048,5553527613,None,None,Fijo,19.478754,-99.203788,2019-11,denue_09_shp — conjunto_de_datos/denue_inegi_0...,/vsizip/C:\Users\COMIMSA\Downloads\denue_09_sh...,72,Servicios de alojamiento temporal y de prepara...,722,Servicios de preparación de alimentos y bebidas,7225,Servicios de preparación de alimentos y bebida...,72251,Servicios de preparación de alimentos y bebida...,Restaurantes con servicio de preparación de pi...,POINT (478613.424 2153814.635),NaN
1,11105620,09002722514006101000000000U4,TACOS BORRACHOS,None,722514,Restaurantes con servicio de preparaci�n de ta...,0 a 5 personas,CALLE,NORTE 45,CALLE,NORTE 45,CALLE,PONIENTE 134,CALLE,PONIENTE 134,None,SN,None,None,None,None,COLONIA,INDUSTRIAL VALLEJO,None,None,None,02300,09,Ciudad de M�xico,002,Azcapotzalco,0001,Azcapotzalco,0877,009,None,None,None,Semifijo,19.494050,-99.159379,2024-11,denue_09_shp — conjunto_de_datos/denue_inegi_0...,/vsizip/C:\Users\COMIMSA\Downloads\denue_09_sh...,72,Servicios de alojamiento temporal y de prepara...,722,Servicios de preparación de alimentos y bebidas,7225,Servicios de preparación de alimentos y bebida...,72251,Servicios de preparación de alimentos y bebida...,Restaurantes con servicio de preparación de ta...,POINT (483275.514 2155502.245),NaN
2,652551,09005811219000291000000000U0,ESPI,None,466211,"Comercio al por menor de mobiliario, equipo y ...",0 a 5 personas,CALLE,21,CALLE,PERLILLAR,EJE VIAL,CENTRAL (LAZARO CARDENAS),CALLE,20,2,None,None,None,0,None,COLONIA,PRO NACIONAL,None,None,None,07600,09,Ciudad de M�xico,005,Gustavo A. Madero,0001,Gustavo A. Madero,0440,024,None,None,None,Fijo,19.517233,-99.155983,2010-07,denue_09_shp — conjunto_de_datos/denue_inegi_0...,/vsizip/C:\Users\COMIMSA\Downloads\denue_09_sh...,46,Comercio al por menor,466,"Comercio al por menor de enseres domésticos, c...",4662,"Comercio al por menor de mobiliario, equipo y ...",46621,"Comercio al por menor de mobiliario, equipo y ...","Comercio al por menor de mobiliario, equipo y ...",POINT (483634.142 2158067.197),"Tecnología, informática y telecomunicaciones"
3,11795606,09016462112003721000000000U9,EL SANTO GALLO CREMERIA Y ABARROTES,None,462112,Comercio al por menor en minisupers,0 a 5 personas,CALLE,Lago Caneguin,CALLE,Lago Chiem,CALLE,Lago Biwa,CALLE,Felipe Carrillo Puerto,31,None,None,None,None,None,COLONIA,PENSIL NORTE,None,None,None,11440,09,Ciudad de M�xico,016,Miguel Hidalgo,0001,Miguel Hidalgo,1334,014,None,None,None,Fijo,19.452121,-99.190881,2025-04,denue_09_shp — conjunto_de_datos/denue_inegi_0...,/vsizip/C:\Users\COMIMSA\Downloads\denue_09_sh...,46,Comercio al por menor,462,Comercio al por menor en tiendas de autoservic...,4621,Comercio al por menor en tiendas de autoservicio,46211,Comercio al por menor en tiendas de autoservicio,Comercio al por menor en minisupers,POINT (479964.614 2150866.005),NaN
4,667545,09002722514002031000000000U7,PIZZAS Y AGUAS FERRERIA SEMIFIJO,None,722514,Restaurantes con servicio de preparaci�n de ta...,0 a 5 personas,CALLE,CALZADA AZCAPOTZALCO LA VILLA,CALLE,4 DE AGOSTO,EJE VIAL,4 NORTE (CALZADA AZCAPOTZALCO LA VILLA),CALZADA,SANTO TOMAS,0,SN,None,None,None,None,COLONIA,SANTO TOMAS,None,None,None,02020,09,Ciudad de M�xico,002,Azcapotzalco,0001,Azcapotzalco,0330,001,None,None,None,Semifijo,19.485515,-99.180337,2010-07,denue_09_shp — conjunto_de_datos/denue_inegi_0...,/vsizip/C:\Users\COMIMSA\Downloads\denue_09_sh...,72,Servicios de alojamiento temporal y de prepara...,722,Servicios de preparación de alimentos y bebidas,7225,Servicios de preparación de alimentos y bebida...,72251,Servicios de preparación de alimentos y bebida...,Restaurantes con servicio de preparación de ta...,POINT (481075.2 2154559.944),NaN

In [9]:
denue['categoria_cdit'].value_counts()

categoria_cdit
Servicios profesionales, científicos y técnicos    569
Tecnología, informática y telecomunicaciones       481
Apoyo a negocios y emprendimiento                  362
Educación y capacitación                           306
Manufactura tecnológica e industria avanzada       262
Diseño y economía creativa                         220
Name: count, dtype: int64

In [10]:
denue_cdit = denue[denue['categoria_cdit'].notna()].copy()
print(f"Total unidades económicas en la zona: {len(denue)}")
print(f"Total unidades económicas en la zona con categoría CDIT: {len(denue_cdit)}")
denue_cdit.head()

Total unidades económicas en la zona: 37459
Total unidades económicas en la zona con categoría CDIT: 2200

,id,clee,nom_estab,raz_social,codigo_act,nombre_act,per_ocu,tipo_vial,nom_vial,tipo_v_e_1,nom_v_e_1,tipo_v_e_2,nom_v_e_2,tipo_v_e_3,nom_v_e_3,numero_ext,letra_ext,edificio,edificio_e,numero_int,letra_int,tipo_asent,nomb_asent,tipoCenCom,nom_CenCom,num_local,cod_postal,cve_ent,entidad,cve_mun,municipio,cve_loc,localidad,ageb,manzana,telefono,correoelec,www,tipoUniEco,latitud,longitud,fecha_alta,layer,path,cod_sector,sector,cod_subsector,subsector,cod_rama,rama,cod_subrama,subrama,clase,geometry,categoria_cdit
2,652551,09005811219000291000000000U0,ESPI,None,466211,"Comercio al por menor de mobiliario, equipo y ...",0 a 5 personas,CALLE,21,CALLE,PERLILLAR,EJE VIAL,CENTRAL (LAZARO CARDENAS),CALLE,20,2,None,None,None,0,None,COLONIA,PRO NACIONAL,None,None,None,07600,09,Ciudad de M�xico,005,Gustavo A. Madero,0001,Gustavo A. Madero,0440,024,None,None,None,Fijo,19.517233,-99.155983,2010-07,denue_09_shp — conjunto_de_datos/denue_inegi_0...,/vsizip/C:\Users\COMIMSA\Downloads\denue_09_sh...,46,Comercio al por menor,466,"Comercio al por menor de enseres domésticos, c...",4662,"Comercio al por menor de mobiliario, equipo y ...",46621,"Comercio al por menor de mobiliario, equipo y ...","Comercio al por menor de mobiliario, equipo y ...",POINT (483634.142 2158067.197),"Tecnología, informática y telecomunicaciones"
112,9704974,15104611611000771000000000U4,CLASES DE MUSICA,None,611611,Escuelas de arte del sector privado,0 a 5 personas,CALLE,CALLE DEL CRISTO,AVENIDA,SANTA MONICA,CALLE,DIEZ DE MAYO,CALLE,VIA GUSTAVO BAZ,10,None,None,None,None,None,COLONIA,EL MIRADOR,None,None,None,54080,15,M�xico,104,Tlalnepantla de Baz,0001,Tlalnepantla,0961,006,5537643645,LAAXX@GMAIL.COM,None,Fijo,19.512164,-99.219365,2024-11,denue_15_2_shp — conjunto_de_datos/denue_inegi...,/vsizip/C:\Users\COMIMSA\Downloads\denue_15_2_...,61,Servicios educativos,611,Servicios educativos,6116,Otros servicios educativos,61161,Escuelas de arte,Escuelas de arte del sector privado,POINT (476983.38 2157513.527),Educación y capacitación
116,7157944,15104561320000091000000000S5,MDC EMPLEOS,MDC EMPLEOS SC,561320,Agencias de empleo temporal,0 a 5 personas,CALLE,VIA GUSTAVO BAZ,CALLE,DIEZ DE MAYO,AVENIDA,SANTA MONICA,CALLE,CALLE DEL CRISTO,47,None,None,None,2,None,COLONIA,EL MIRADOR,None,None,None,54080,15,M�xico,104,Tlalnepantla de Baz,0001,Tlalnepantla,0961,006,5544949940,CONTACTO@MDCEMPLEOS.COM,WWW.MDCEMPLEOS.COM,Fijo,19.511457,-99.218199,2019-11,denue_15_2_shp — conjunto_de_datos/denue_inegi...,/vsizip/C:\Users\COMIMSA\Downloads\denue_15_2_...,56,Servicios de apoyo a los negocios y manejo de ...,561,Servicios de apoyo a los negocios,5613,Servicios de empleo,56132,Agencias de empleo temporal,Agencias de empleo temporal,POINT (477105.632 2157435.165),Apoyo a negocios y emprendimiento
169,6778012,15104561310000383000002692S7,MARKET PRO,MARKET PRO SA DE CV,561310,Agencias de colocaci�n,51 a 100 personas,CALLE,FRANCISCO I. MADERO,CALLE,EMILIANO ZAPATA,CALLE,L�ZARO C�RDENAS,CALLE,MONSERRAT,220,None,None,None,None,None,COLONIA,SAN JERONIMO TEPETLACALCO,None,None,None,54090,15,M�xico,104,Tlalnepantla de Baz,0001,Tlalnepantla,1940,023,None,ALANDA@MARKETPRO.COM.MX,None,Fijo,19.513968,-99.211243,2017-03,denue_15_2_shp — conjunto_de_datos/denue_inegi...,/vsizip/C:\Users\COMIMSA\Downloads\denue_15_2_...,56,Servicios de apoyo a los negocios y manejo de ...,561,Servicios de apoyo a los negocios,5613,Servicios de empleo,56131,Agencias de colocación,Agencias de colocación,POINT (477835.767 2157712.136),Apoyo a negocios y emprendimiento
170,8696631,15104713113000032000000000U5,ACUATICA EL ROSARIO TLALLI II,None,611621,Escuelas de deporte del sector privado,11 a 30 personas,CALLE,FRANCISCO DEL PASO Y TRONCOSO,CALLE,NINGUNO,AVENIDA,LAS ARMAS NORTE,AVENIDA,CULTURA GRIEGA,2,None,None,None,None,None,COLONIA,EL ROSARIO,None,None,None,54090,15,M�xico,104,Tlalnepantla de Baz,0001,Tlalnepantla,1851,007,5550846064,None,WWW.ACUATICA.COM.MX,Fijo,19.517062,-99.201886,2019-11,denue_15_2_shp — conjunto_de_datos/denue_inegi...,/vsizip/C:\Users\COMIMSA\Downloads\denue_15_2_...,61,Servicios educativos,611,Servicios educativos,6116,Otros servicios educativos,61162,Escuelas de deporte,Escuelas de deporte del sector privado,POINT (478817.955 2158053.339),Educación y capacitación

In [11]:
denue_cdit.to_crs(epsg=4326).to_file('../docs/datos/unidades_economicas_cdit_2025.geojson')